version: "3"



services:
  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      grafana.example.com: "192.168.50.155"
    
