{
 "title": "ShoeHub",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(shoehub_payments, CountryCode)"
    }
   },
   {
    "name": "paymentMethod",
    "label": "Payment Method",
    "query": {
     "query": "label_values(  shoehub_payments, PaymentMethod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Tech Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU consumption",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum  (rate(node_cpu_seconds_total{mode!=\"idle\"}[30s]) ) / scalar (count(group(node_cpu_seconds_total) by (cpu))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(microsoft_aspnetcore_hosting_http_server_request_duration_sum[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Error Database",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count_over_time({level=\"ERROR\", component=\"database\"} |= `` [10m])",
     "legendFormat": "Error last 5m"
    }
   ]
  },
  {
   "title": "Error Log Message last 3 hours",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{level=\"ERROR\"} |= ``"
    }
   ]
  },
  {
   "title": "Error message ratio",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate({component=\"database\", level=\"ERROR\"} |= ``[5m])",
     "legendFormat": "database error"
    },
    {
     "expr": "rate({component=\"backend\", level=\"ERROR\"} |= ``[5m])",
     "legendFormat": "backend"
    },
    {
     "expr": "rate({component=\"UI\", level=\"ERROR\"} |= ``[5m])",
     "legendFormat": "UI"
    }
   ]
  },
  { "title": "Business Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Payment [$country]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Card\"}[5m])",
     "legendFormat": "Card"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Cash\"}[5m])",
     "legendFormat": "Cash"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Paypal\"}[5m])",
     "legendFormat": "PayPal"
    }
   ]
  },
  {
   "title": "Payments [$country]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Card\"}[1m])",
     "legendFormat": "Card"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Paypal\"}[1m])",
     "legendFormat": "Paypal"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Cash\"}[1m])",
     "legendFormat": "Cash"
    }
   ]
  },
  {
   "title": "Sales",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Boots\"}[1m])",
     "legendFormat": "boots"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"HighHeels\"}[1m])",
     "legendFormat": "HighHeels"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[1m])",
     "legendFormat": "Loafers"
    },
    {
     "expr": "scalar(rate(shoehub_sales{ShoeType=\"Boots\"}[1m])) + scalar(rate(shoehub_sales{ShoeType=\"HighHeels\"}[1m])) + scalar(rate(shoehub_sales{ShoeType=\"Loafers\"}[1m]))",
     "legendFormat": "total_sales"
    }
   ]
  },
  {
   "title": "Sale Today vs Sale last week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[1m])",
     "legendFormat": "now"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[1m] offset 2m)",
     "legendFormat": "delay"
    }
   ]
  },
  {
   "title": "Is Paypal justified in $country?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Card\"} ) / sum(shoehub_payments{CountryCode=\"$country\"} ) * 100",
     "legendFormat": "Card"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Cash\"} ) / sum(shoehub_payments{CountryCode=\"$country\"} ) * 100",
     "legendFormat": "Cash"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Paypal\"} ) / sum(shoehub_payments{CountryCode=\"$country\"} ) * 100",
     "legendFormat": "Paypal"
    }
   ]
  },
  {
   "title": "Payment Amount [$paymentMethod]",
   "type": "timeseries",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 50 },
   "repeat": "paymentMethod",
   "targets": [
    {
     "expr": "  shoehub_payments{PaymentMethod=\"$paymentMethod\"}",
     "legendFormat": "{{CountryCode}}-{{PaymentMethod}}"
    }
   ]
  },
  {
   "title": "Payment Amount by method of $paymentMethod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "repeat": "paymentMethod",
   "targets": [
    {
     "expr": "  shoehub_payments{PaymentMethod=\"$paymentMethod\"}",
     "legendFormat": "{{CountryCode}}"
    }
   ]
  }
 ]
}