#https://hub.docker.com/r/linuxserver/rdesktop
---
services:
  rdesktop:
    image: linuxserver/rdesktop:ubuntu-kde-version-a34093e0
    container_name: rdesktop
    # security_opt:
    #   - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3389:3389
    restart: unless-stopped
