version: "3.1"
#example: https://hevodata.com/learn/docker-postgresql/#step2
services:
  postgres:
    container_name: postgres
    image: postgres:alpine3.16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "$PWD/postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "boar"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - backend
networks:
  backend:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::1    