version: "3"


services:
  nginx:
    image: nginx:latest
    container_name: demo
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./site-content:/usr/share/nginx/html


