apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresdb
  name: postgresdb
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb-volatile
  template:
    metadata:
      labels:
        app: postgresdb-volatile
    spec:
      containers:
      - image: postgres:alpine3.16
        name: postgres
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "1024m"
            memory: "1Gi"
        env:
          - name: POSTGRES_USER
            value: "boar"
          - name: POSTGRES_PASSWORD
            value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresdb
  name: postgresdb-service
  namespace: database
spec:
  ports:
  - port: 5431
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresdb-volatile
  type: LoadBalancer

