apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresdb
  name: postgresdb-service
  namespace: database
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresdb-volatile
  type: LoadBalancer
